import { defineRouteConfig } from "@medusajs/admin-sdk"
import { Sparkles } from "@medusajs/icons"
import { Container, Heading, Text, Table } from "@medusajs/ui"
import { useQuery } from "@tanstack/react-query"

export const config = defineRouteConfig({
  label: "Visualizations",
  icon: Sparkles,
})

export default function VisualizationsPage() {
  const { data, isLoading } = useQuery({
    queryKey: ["visualizer_results"],
    queryFn: async () => {
      // In Medusa Admin, relative paths work for admin API endpoints
      const res = await fetch("/admin/visualizations")
      return res.json()
    }
  })

  return (
    <Container className="p-8">
      <Heading level="h1" className="mb-4">AI Visualizations History</Heading>
      <Text className="text-ui-fg-subtle mb-8">
        View the custom room setups generated by your customers using the AI Rug Visualizer.
      </Text>

      {isLoading ? (
        <Text>Loading visualizations...</Text>
      ) : (
        <Table>
          <Table.Header>
            <Table.Row>
              <Table.HeaderCell>Customer Name</Table.HeaderCell>
              <Table.HeaderCell>Customer ID</Table.HeaderCell>
              <Table.HeaderCell>Generated Image</Table.HeaderCell>
              <Table.HeaderCell>Date</Table.HeaderCell>
            </Table.Row>
          </Table.Header>
          <Table.Body>
            {data?.visualizer_results?.map((result: any) => (
              <Table.Row key={result.id}>
                <Table.Cell className="font-semibold">{result.customer_name || result.customerName}</Table.Cell>
                <Table.Cell className="text-ui-fg-muted">{result.customer_id || result.customerId}</Table.Cell>
                <Table.Cell>
                  <a href={result.image_url || result.imageUrl} target="_blank" rel="noreferrer">
                    <img 
                      src={result.image_url || result.imageUrl} 
                      alt="Generated setup" 
                      className="w-32 h-20 object-cover rounded-md border border-ui-border-base hover:scale-150 transition-transform origin-left z-10 relative"
                    />
                  </a>
                </Table.Cell>
                <Table.Cell>
                  {new Date(result.created_at || result.createdAt).toLocaleString()}
                </Table.Cell>
              </Table.Row>
            ))}
          </Table.Body>
        </Table>
      )}
    </Container>
  )
}
